// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5BEDNbXzTUOa2WxO25HyFpmyT4iPcWso',
    appId: '1:180711058554:web:3d4f9480c7f492e9a4dfc3',
    messagingSenderId: '180711058554',
    projectId: 'vibematch-6ddcd',
    authDomain: 'vibematch-6ddcd.firebaseapp.com',
    storageBucket: 'vibematch-6ddcd.appspot.com',
    measurementId: 'G-SZQYNSSH46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC91ikMcoRCLjOfaystIXTm1F_fyvkCKTc',
    appId: '1:180711058554:android:e192270d89307aa9a4dfc3',
    messagingSenderId: '180711058554',
    projectId: 'vibematch-6ddcd',
    storageBucket: 'vibematch-6ddcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQMRgB-wXLZdn69FmRYFB8t-NPhNQmBY',
    appId: '1:180711058554:ios:22596a8cb2641168a4dfc3',
    messagingSenderId: '180711058554',
    projectId: 'vibematch-6ddcd',
    storageBucket: 'vibematch-6ddcd.appspot.com',
    iosBundleId: 'com.example.vibematchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxQMRgB-wXLZdn69FmRYFB8t-NPhNQmBY',
    appId: '1:180711058554:ios:22596a8cb2641168a4dfc3',
    messagingSenderId: '180711058554',
    projectId: 'vibematch-6ddcd',
    storageBucket: 'vibematch-6ddcd.appspot.com',
    iosBundleId: 'com.example.vibematchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5BEDNbXzTUOa2WxO25HyFpmyT4iPcWso',
    appId: '1:180711058554:web:0c2367c9dee774e2a4dfc3',
    messagingSenderId: '180711058554',
    projectId: 'vibematch-6ddcd',
    authDomain: 'vibematch-6ddcd.firebaseapp.com',
    storageBucket: 'vibematch-6ddcd.appspot.com',
    measurementId: 'G-44E3CZKV11',
  );
}
